### PR TITLE
Add project plan for 451

### LINKED ISSUE #85: Update Project Plan
**Documentation description:**
After a discussion with the team, we've decided on our project plan. Yet, the project plan needs to be imported to either ProjectLibre or Microsoft Projects. The deadline for this task is 07.11.2020. 

**Document source**:
https://docs.google.com/spreadsheets/d/1nWzgpoKbpbMr30RRlbOMJINDnAKPOU-UKyblHG3HOnY/edit#gid=0

### PR DESCRIPTION
**Pull request by nursimacelik**

### CODE REVIEW

**Comment by afraarslan** [comment]
* The finish date of deployment for all three groups(Backend, Front-end, Mobile) is written as 25th November. But our first milestone is on 24th November. It should be before the Milestone#1.
* I think milestones will depend on all the work we have done so far. So, we can set the predecessors of Milestones the last jobs of the three groups. Also, it can be assigned to everyone.
😊

**Comment by oztasozgurcan** [comment]
I agree with @afraarslan, date correction is needed in the project plan. The rest is great, thanks! 👍

**Review by oztasoi — CHANGES_REQUESTED** [review]
I agree with @afraarslan, date correction is needed in the project plan. The rest is great, thanks! 👍

**Comment by nursimacelik** [comment]
Project plan is updated according to the discussions in the lab meeting (10.11.2020 15.00) and another meeting we did for the project plan (11.11.2020 00.00).

**Review by oztasoi — APPROVED** [review]
These screenshots and .pdf files are justifies our plan in a _well-documented manner_.
**Kudos 💯**

**Review by afraarslan — APPROVED** [review]
Good job! 👍

**Comment by ykaya932** [comment]
It looks great, thanks @nursimacelik!

**Comment by ykaya932** [comment]
Oh, I thought closing will be same as the approving :)

**Review by ykaya932 — APPROVED** [review]
I haven't spotted any issue, thanks again!

**Pull request merged**
