### PR TITLE
Backend feature/add purchase

### PR DESCRIPTION
**Pull request by burakberk**
Implemented purchase and order get functionality

Endpoint:

customer/purchase -> parameters: _id, shippingAddressId, billingAddressId, creditCardId

Example request body:

```
{	
	"_id" : "5fd7ae30edd1504b481ef463",
	"shippingAddressId": "5fe91753ab14c0121ae7eab8",
	"billingAddressId": "5fe91753ab14c0121ae7eab8",
	"creditCardId": "5fe91c6548c5cec4b5e2bbc9"
}
```
customer/order/getByCustomerID -> parameters: customerID

Example request body:

`{ "customerID": "5fd7ae30edd1504b481ef463" }`

Example requests can be accessed from this [postman collection.](https://www.getpostman.com/collections/6876df5b7d234c74812f)

### CODE REVIEW

**Review by oztasoi — CHANGES_REQUESTED** [review]
In this implementations, you've gone a a different way than general structure of our code repository. To check a condition, add a validator in AppValidator.js and use the validations here, then check for errors and finally use then() to call the related service function.

**Comment by burakberk** [comment]
Refactored controllers to be more inline with conventions of the repo.

**Review by oztasoi — APPROVED** [review]
For now, this is sufficient to move further. Good job!

**Comment by burakberk** [comment]
Thanks for the feedback, merging into the backend.

**Pull request merged**
