### PR TITLE
Milestone 1 Report

### PR DESCRIPTION
**Pull request by oztasoi**
Uploaded Milestone 1 Report

### CODE REVIEW

**Review by oncelkeles — APPROVED** [review]
Great job everyone! Now lets move on to the second milestone 🔥

**Review by afraarslan — APPROVED** [review]
Thanks to everyone for your effort

**Review by ahmetyigitgedik — APPROVED** [review]
So good so far. The future is exciting 💯

**Comment by ykaya932** [comment]
Nicely done!! Thanks, everyone 💯

**Review by ykaya932 — APPROVED** [review]

**Pull request merged**
