### PR TITLE
Web feature/order cart list

### PR DESCRIPTION
**Pull request by afraarslan**
* Integrated list and cart endpoints
* Some UI changes are made according to API responses.
* Create order pages UI.

**Designs**

image
--------

image
--------

image

**Notes**
There are some missing points. We can complete and enhance them in the next days.

### CODE REVIEW

**Comment by oncelkeles** [comment]
There some things I like to point out:

- The div where we show the total price while purchasing does not change according to the products in the cart, it should change however.
- After purchasing, I think the cart should reset.
- In a product's page, I can't add the product to any list with the "like" button.
- After purchasing, it might be better to redirect the user to the order page in terms of ux.
- There is also something wrong with the List button in the Header. When clicked, it redirects to the Login page but still keeps the user logged in. This might be an unrelated issue to this PR, but we should check it out.

Apart from these points, I think the overall implementation is really sweet, thanks for the hard work!

**Comment by afraarslan** [comment]
I added the points  that I missed;
* Total price and the shipment price is shown now on the right side of the cart page.
* The total price and the total amount is also shown on the order page.
* After purchasing, the cart resets.
* After purchasing, it redirects the user to the order page

I also fixed this bug;
* There is also something wrong with the List button in the Header. When clicked, it redirects to the Login page but still keeps the user logged in. 

Still missing;
* On a product's page, I can't add the product to any list with the "like" button.
This can be enhanced in another branch since it is on a different page. To add a product to a list, you can use the postman collection.

**Comment by ykaya932** [comment]
Excellent work! The only small issue I've noticed is, there is no dollar sign in the order sidebar. After adding the dollar sign, we are ready to go 🚢 
image

**Review by ykaya932 — APPROVED** [review]
Outstanding work! 🥇

**Pull request merged**
