### PR TITLE
Create a home page

### PR DESCRIPTION
**Pull request by nursimacelik**
home

A home page for the website.

### CODE REVIEW

**Comment by burakberk** [comment]
__pycache__ files should be removed from request

**Comment by nursimacelik** [comment]
> **pycache** files should be removed from request

According to [this](https://stackoverflow.com/questions/16869024/what-is-pycache) post on Stackoverflow: if deleted, they are recreated during run. I think they are not necessary for deployment.

**Comment by burakberk** [comment]
Yes, they will be dynamically created during run according to curreny .py files. That is why we don't need to commit them, they would just pollute commit history.

**Comment by nursimacelik** [comment]
So, I should change .gitignore later?

Just in case there is a misunderstanding, I am deleting them not adding.

**Comment by burakberk** [comment]
I see, you can add all .pyc type files to your .gitignore. 

Since deleting them does not do any harm and rest of the code is good to go, I am merging this pull request.

**Comment by burakberk** [comment]
Closed unintentionally, merging now.

**Pull request merged**
