### PR TITLE
Web feature/guest transactions

### LINKED ISSUE #469: Add to cart for guest users
**Describe the feature**
Guest users should be able to add products to their carts.

### LINKED ISSUE #482: Guest user purchase
**Describe the feature**
Guest users should be able to purchase the products in their cart.

**Describe solutions you've considered**
The guest users do not have stored address and credit cart information, so they will be asked at the purchase confirm page.

### PR DESCRIPTION
**Pull request by oncelkeles**
The purchase flow for the guest users is done. See issue #469 and #482 .

The guest users can now add products to cart and purchase them if they want to. The email address, shipping address and payment info is taken at the purchase stage one-by-one.

Screen Shot 2021-01-25 at 04 31 17

Screen Shot 2021-01-25 at 04 31 24

Screen Shot 2021-01-25 at 04 31 34

Screen Shot 2021-01-25 at 04 31 47

There might be some ux updates afterwards if enough time remains.

### CODE REVIEW

**Review by ykaya932 — CHANGES_REQUESTED** [review]
I tried to add some products with the guest user, but unfortunately, it gave me an error. I think it is due to the `login` is not exists in the local storage, when a user enters the website for the first time.

**Review by ykaya932 — APPROVED** [review]
Latest commit should handle the issue I talked about. Great job @oncelkeles, it looks fascinating!! 🚀

**Comment by oncelkeles** [comment]
> Latest commit should handle the issue I talked about. Great job @oncelkeles, it looks fascinating!! 🚀

Thanks for fixing it Yasin 🥇

**Review by afraarslan — COMMENTED** [review]
I love this note :smile: 

image

**Pull request merged**
