### PR TITLE
Add models for mainProduct and products

### LINKED ISSUE #258: Add mainProduct and product models and necessary endpoints
**Describe the feature**
We need to create product and mainProduct models. Also their related files should be implemented in routers, controllers, dataAccesses and services.

**Describe solutions you've considered**
With only product and mainProduct vendors aren't able to request changes on the products. So, we will also need to create productRequest model for vendors to be able to request creation, update and delete of their products. This models will also need new files in routers, controllers, dataAccesses and services folders. The api request flow will be as follows:
- A vendor may request to create, delete or update its products. This request will create productRequest documents that will be available only to admins and that vendor. 
- An admin can deny or accept the request. If they accept, they send an api request that will make necessary changes in the mainProduct and product documents. If they deny the request, the vendor will be notified of the decision along with admin's reasoning. Admins also can delete requests they deem unreasonable.
- Then vendor may decide to delete the request or they can modify it and send it for approval again.

### PR DESCRIPTION
**Pull request by mtyazici**
Created the initial models for products. Also created all the related files in router, dataAccess, controller and services folders. I tested every endpoint's functionality. 
Added enpoints are:
### For Main Product
Main products hold the common information about all of its sub products, it has `parameters` field whose any combination can be a new product. Ex. parameters = [{"name": "color", "values" : ["blue","red"]},{"name": "size", "values" : ["L","M"]} ]. This main product can have 4 products which are connected to this one. If parameters is empty only one product is connected to the mainProduct.
- GET /mainProduct
- POST /mainProduct
--------------------------------------------------------------------------------------------------
- GET /mainProduct/:id
- PATCH /mainProduct/:id
- DELETE /mainProduct/:id
---------------------------------------------------------------------------------------------------
- DELETE /mainProduct/:mpid/vendor/:vid

### For Product
Products can have multiple sellers their information is hold in an array called `vendorSpecifics`.
- GET /product/search -> now empty, needs to be implemented
---------------------------------------------------------------------------------------------------
- GET /product
- POST /product
---------------------------------------------------------------------------------------------------
- GET /product/:id
- POST /product/:id
- PATCH /product/:id
- DELETE /product/:id
---------------------------------------------------------------------------------------------------
- DELETE product/:pid/vendor/:vid     -> Deletes vendor from product
- PATCH product/:pid/vendor/:vid        -> Updates vendor's data in the product

### For ProductRequest
Vendors can't directly make modifications to their products, the actions they take about their product create productRequests which then goes to admins for their approval.
- GET /productRequest
----------------------------------------------------------------------------------------------------
- GET /productRequest/:id
- PATCH /productRequest/:id
- DELETE /productRequest/:id

### For Vendor
- GET /vendor/me/product
----------------------------------------------------------------------------------------------------
- GET /vendor/me/product/:id         -> gets the product vendor sells, it is different from `GET /product/:id` because this doesn't return data related to other vendors.
- PATCH /vendor/me/product/:id     -> creates a productRequest for admins to see
- DELETE /vendor/me/product/:id   ->creates a productRequest for admins to see
-----------------------------------------------------------------------------------------------------
- GET /vendor/me/mainProduct                   -> Shows the mainProducts that vendor sells products of
- DELETE /vendor/me/mainProduct/:mpid  -> creates a productRequest for admins to see
----------------------------------------------------------------------------------------------------
- POST /vendor/me/product/new            -> creates a productRequest for admins to see
- POST /vendor/me/product/existing/:id  -> creates a productRequest for admins to see
-----------------------------------------------------------------------------------------------------
- GET /vendor/me/productRequest    -> shows all the productRequests vendor created
----------------------------------------------------------------------------------------------------
- GET /vendor/me/productRequest/:id
- PATCH /vendor/me/productRequest/:id
- DELETE /vendor/me/productRequest/:id

Note: I was planning to write documentation for these endpoints however the `swagger.json` is already at 1500 lines. We need to find a way to split up the documentation files to make them managable, if I added these endpoints now it would be nearly impossible to keep track of things.

Note 2: The return values of updates for `productDataAccess` aren't really updated because I use `find` then modify the documents locally in the callback function, the value we return doesn't show the updated document but the updates are present on the database. We could try to solve it by using other functions. However I couldn't find a solution for it under the time constraint I had for implementation.

Note 3: We need to add filtering fields to products, we should discuss it on how to implement it.

### CODE REVIEW

**Review by oztasoi — COMMENTED** [review]
I've inspected the product model, yet I've questions to discuss within our team. Let's discuss the model.

**Comment by mtyazici** [comment]
You can see the enpoints in POSTMAN: https://www.getpostman.com/collections/bf3f8631ccf940b001a5

**Review by oztasoi — APPROVED** [review]
Magnificent work, nothing more to say 🔥 🚀

**Comment by mtyazici** [comment]
Lets hope for the best :D

**Pull request merged**
