### PR TITLE
Fixed alert message shown before confirm deletion

### PR DESCRIPTION
**Pull request by oncelkeles**
See issue #570 for the bug description.

With this PR, the delete request message will be shown after confirming in the pop-up, using the message component of antd.

### CODE REVIEW

**Review by ykaya932 — DISMISSED** [review]
Thanks for noticing and fixing the issue, it's a nice catch 💯

**Comment by ykaya932** [comment]
I've just noticed a bug when displaying the delete product requests in the admin panel. Since I believe it is related to this PR, I've directly added a commit to this PR.

**Comment by oncelkeles** [comment]
Thanks for noticing another bug while reviewing Yasin! This really shows your passion 🔥

**Review by ykaya932 — APPROVED** [review]
It was a nice issue, we've noticed more than one of our bugs. Well done 🥇

**Pull request merged**
